### ISSUE TITLE
Requirements can not be saved under Manage Course-> specific ranking and selection tools 

### ISSUE THREAD

**Issue by adamslin** [qinscode/UWA-Curriculum-Rules-Management-System#35]
In any course under Manage Course, enter the edit tools, Click the button for "specific ranking and selection tools or requirements" and click "add requirement", type in any words under specific ranking and selection.

After click the save button, it will say "rules saved". But re-enter the course page, the reuquirements newly added for specific ranking and selection disappear.

**Comment by qinscode** [comment]
This issue has been fixed in the latest commit.
